import type { Metadata } from "next";
import { Inter } from "next/font/google";
import CollapsibleMenu from "src/components/collapsible_menu";
import Header from "src/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CollapsibleMenu>
          <Header />
          {children}
        </CollapsibleMenu>
      </body>
    </html>
  );
}
